// react-api/src/App.js
import React from 'react';
//import { Provider } from "mobx-react";
import Anime from './pages/Anime';
import Home from './pages/Home';
//import AnimeStore from "./stores/AnimeStore";
import Footer from './components/Footer';
import Header from './components/Header';
import './styles/App.css';

function App() {
  return (
    //<Provider AnimeStore={AnimeStore}>

    <div>
      <Header />
      <Home />
      <Anime />
      <Footer />
    </div>
    //</Provider>
  );
}

export default App;

// vue-api/src/App.vue
<template>
  <div id="app">
    <Header />
    <router-view></router-view>
    <Footer />
  </div>
</template>

<script>
import Header from "./components/Header.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "App",
  components: {
    Header,
    Footer
  }
};
</script>

<style type="text/css">
@import url('../styles/globals.css');
</style>
